- name: Setup YUM repos for NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: add application user
  ansible.builtin.user:
    name: roboshop
    comment: adding application user to roboshop project



