---
- name: configure yum repo
  ansible.builtin.shell: curl -fSsL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add RooShop App USer
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Application User

- name: download and extract
  include_role:
    name: common
    tasks_from: download

- name: Create app directory
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: directory
  become_user: roboshop

- name: cleanup the content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: copy app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: install NodeJs Dependencies
  become_user: roboshop
  community.general.npm:
    path: /home/roboshop/catalogue




