-  name: install nginx
   ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing node JS
  ansible.builtin.yum:
    Name: install Nodejs
      - nodejs
      - gcc-c++
    state: installed




