-  name: setup nodejs
   ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_18.x | bash -


- name: Installing node JS
  ansible.builtin.yum:
    name:
      - libstdc++
    state: installed





