---
- name: Add node.js repo
  yum_repository:
    name: nodejs
    description: Node JS
    baseurl: https://rpm.nodesource.com/pub_8.x/el/7/x86_64/
    enabled: 1
    gpgcheck: 1
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL

- name: Install package
  yum:
    name:
      - https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: present

- name: Install nodejs
  yum:
    name: nodejs-8.*
    state: present
    enablerepo: 'nodesource'


- name: Add RooShop App USer
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Application User


- name: cleanup the content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: copy app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop





