- name: setup nodejs
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -


- name: Install NodeJS
  ansible.builtin.dnf:
    name:
      - gcc-c++
      - nodejs
    state: installed





