- name: configure yum repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -

- name: install node js
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: add application user
  ansible.builtin.user:
    name: roboshop
    comment: adding applpcation user to roboshop application



